## numpy

Use the following code for the questions below:

In [58]:
import numpy  as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [26]:
len(a[a<0])

4

2. How many positive numbers are there?

In [27]:
len(a[a>0])

5

3. How many even positive numbers are there?

In [31]:
len(a[(a%2)==0])

8

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [73]:
# b = [a + 3]
# len(b[(b%2)==0])

len( a[((a + 3) > 0)])

10

5. If you squared each number, what would the new mean and standard deviation be?

In [55]:
 np.mean(a ** 2), np.std(a ** 2)

(74.0, 144.0243035046516)

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [67]:
mean_array = np.mean(a)
print(mean_array)

3.0


In [69]:
center_array = a - mean_array

print (center_array)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [70]:
np.mean(center_array)

0.0

In [74]:
centered = (a - (np.mean(a)))
print(centered)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [76]:
import scipy.stats as stats
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## More Numpy Practice

### Life w/o numpy to life with numpy. Use python's built in functionality/operators to determine the following:

#### Setup 1


In [77]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [89]:
sum_of_a = sum(a)
print(sum_of_a)


55


Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [92]:
min_of_a = min(a)
print(min_of_a)

1


Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [94]:
max_of_a = max(a)
print(max_of_a)

10


Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [ ]:
mean_of 